DROP TABLE USERS;

CREATE TABLE "USERS" (
"ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	"USERNAME" VARCHAR(25) NOT NULL,
	"PASSWORD" VARCHAR(25) NOT NULL,
	CONSTRAINT primary_key_credentials PRIMARY KEY (ID)
);

INSERT INTO USERS(USERNAME,PASSWORD) VALUES('admin','admin');